### ISSUE TITLE
CircuitPython Port

### ISSUE THREAD

**Issue by scath999** [miketeachman/micropython-ads1219#2]
Hi there,

Thanks for posting this!

Having some trouble porting this driver to CircuitPython. 

Translation between these two platforms should be relatively straightforward, but I'm consistently getting `OSError: [Errno 5] Input/output error`.

Unsure if this is because MicroPython uses `ustruct` while CircuitPython uses `struct`, or if there's some other issue that could be at play.

Wondering if you have any guidance here?

**Comment by miketeachman** [comment]
Is it possible to share your code and the exception message that is reported?  That might help to identify the incompatibility.

**Comment by scath999** [comment]
Absolutely - and thanks for getting back to me!

I've mangled some of your code while trying to diagnose the issue myself - this has included consulting the TI forums for some
[support](https://e2e.ti.com/support/data-converters-group/data-converters/f/data-converters-forum/746230/ads1219-pseudo-code?tisearch=e2e-sitesearch&keymatch=ads1219#).

At the moment I can successfully send a RESET command using the following

```python
def __init__(self, i2c, address=0x40):
        
        self._i2c = i2c
        self._address = address
        while not i2c.try_lock():
            print ("Waiting for I2C lock in ADS1219 Driver")

        data = struct.pack('B', _COMMAND_RESET)
        self._i2c.writeto(0x80, data)
        print ("done")
```

Note: the address `0x80` is `0x40` shifted left 1 bit - as advised by the link above.

However, trying to take any other action gives me an `OSError: [Errno 5] Input/output error`

For example:

```python

...
       rreg = struct.pack('B', _COMMAND_RREG_CONFIG) 
       self._i2c.writeto(0x80, rreg)
       print("done sending RREG_CONFIG command")
```

Please let me know if I can provide any other info. 

Thanks again,

S.

How

**Comment by miketeachman** [comment]
> Note: the address `0x80` is `0x40` shifted left 1 bit - as advised by the link above.

You don't need to shift the address.  That is done by the I2C protocol driver.  Figure 8 in https://www.ti.com/lit/an/slva704/slva704.pdf shows this.  When the address = 0x40, the low level I2C driver puts the device address onto the bus as 0x80 (left shifted by one bit).

**Comment by miketeachman** [comment]
Have you done an I2C scan?
i2c = machine.I2C(...)
i2c.scan()

that should return with the I2C address of the ADC.  A scan is the first thing I do when debugging I2C issues.

**Comment by scath999** [comment]
I have done a scan, and I can see both the ads1219 and the other devices I'm using. They continue to work.

I agree that the `write` method should add the `0` or `1` as appropriate, but if I do that I get the OSError mentioned above. I'm thinking that the `0x80` is actually becoming `0x00` - the `1` is probably getting shifted out of the bitstring, making the write a general call.

I've spoken with people in the Adafruit community, and they're as baffled as I am. 

Thoughts?

**Comment by miketeachman** [comment]
Sorry, I'm out of ideas. I've never worked with CircuitPython, so it's hard to help.

**Comment by scath999** [comment]
Figured out the issue: The AVDD jumper was set to 5V, when it should have been set to 3.3V (my reference voltage).

Everything works now - Very sorry for the trouble!

Wondering if you'd like the code? Maybe to post it to the CircuitPython project?

**Comment by miketeachman** [comment]
Yay !    Glad that the driver is working in circuitpython.  Thanks for following up.  You don't need to go the trouble of posting the code.
